%teste
%1 tuple -> class = {'GALAXY'}
amountOfData=1000;
fileName='DataSet.csv';
lineTOEstimate=14;
% 3 -> QSO
% 14 -> STAR
% mostly galaxies
Naive_Bayes_with_gassian_log=0;

pathFile=fullfile('/home/neves-default/Secretária/universidade de Aveiro/2ºano/2º semestre/Metodos_probabilisticos_EI/Projeto/Trabalho_Pratico/',fileName);
dataManager = DataSetManager(pathFile,amountOfData);

dataManager.loadData();
data=dataManager.getData();

machineLearning=Naive_Bayes(data);

selectedData=data(lineTOEstimate,:);
tuple=table( ...
    selectedData.z, ...
    selectedData.spectroFlux_u, ...
    selectedData.spectroFlux_g, ...
    selectedData.spectroFlux_r, ...
    selectedData.spectroFlux_i, ...
    selectedData.spectroFlux_z, ...
    selectedData.velDisp, ...
    selectedData.snMedian_r, ...
    'VariableNames', { ...
        'redshift', ...
        'spectroFlux_u', ...
        'spectroFlux_g', ...
        'spectroFlux_r', ...
        'spectroFlux_i', ...
        'spectroFlux_z', ...
        'velDisp', ...
        'snMedian_r' ...
});
machineLearning.buildFeature();
machineLearning.Average;
machineLearning.StandartDeviation();
machineLearning.getEachClassesData();
class=machineLearning.estimateClass(tuple,Naive_Bayes_with_gassian_log);
disp(class);


%funciona omg :)))))))))))